name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # - name: Create local changes
      #   run: touch test

      # - name: Commit files
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add .
      #     git commit -m "Add changes" -a
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: clone
        run: |
          git config --global user.email "miyauchi@qualitia.co.jp"
          git config --global user.name "miyauci"
          git submodule add https://github.com/miyauci/param.git param
          ls
          pwd
          cd param
          touch tes
          git add .
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
