name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # - name: Create local changes
      #   run: touch test

      # - name: Commit files
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add .
      #     git commit -m "Add changes" -a
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: test
        env:
          hello: 1234
        run: |
          echo ${hello}
      # - name: clone
      #   run: |
      #     git config --global user.email "miyauchi@qualitia.co.jp"
      #     git config --global user.name "miyauchi"
      #     git remote set-url origin https://miyauci:${{secrets.GITHUB_TOKEN}}@github.com/miyauci/param.git
      #     git clone https://miyauci:${{ secrets.GITHUB_TOKEN }}@github.com/miyauci/param.git
      #     cd param
      #     touch tes
      #     git add .
      #     git commit -m "Add changes" -a
      #     git push
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
